# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:8.2
    # For different app you can use different names. (eg: )
    container_name: container-lemp
    volumes:
      # app source code
      - ./app:/var/www/html
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 8080:80
    environment:
      DISABLE: mailcatcher,elasticsearch,pgsql,beanstalkd
      MYSQL_ROOT_PASSWORD: supersecurepwd
      MYSQL_DATABASE: appdb
      MYSQL_USER: dbusr
      MYSQL_PASSWORD: securepwd
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}
