version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "${XP_ENV_PORT:-8654}:80"
        volumes:
            - ./app:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        links:
            - php-fpm

    php-fpm:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app:/var/www/html
        restart: always
