/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    XpBox: typeof import('./src/components/XpBox.vue')['default']
    XpBox1: typeof import('./src/components/XpBox1.vue')['default']
    XpBox2: typeof import('./src/components/XpBox2.vue')['default']
    XpBox3: typeof import('./src/components/XpBox3.vue')['default']
    XpBox4: typeof import('./src/components/XpBox4.vue')['default']
    XpBuilder: typeof import('./src/components/XpBuilder.vue')['default']
    XpDraw: typeof import('./src/components/xpDraw.vue')['default']
    XpForm: typeof import('./src/components/XpForm.vue')['default']
    XpGrid: typeof import('./src/components/XpGrid.vue')['default']
    XpGridCell: typeof import('./src/components/XpGridCell.vue')['default']
    XpMap: typeof import('./src/components/XpMap.vue')['default']
    'XpMapPopup.ce': typeof import('./src/components/XpMapPopup.ce.vue')['default']
  }
}
