version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "${XP_ENV_PORT:-8666}:80"
        volumes:
            - ./app:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        links:
            - php-fpm

    php-fpm:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always
