version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8666:80"
        volumes:
            - ./app:/var/www/html
            - ./my-data:/var/www/my-data
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        links:
            - php-fpm

    php-fpm:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app:/var/www/html
            - ./my-data:/var/www/my-data
        restart: always
