version: "3.9"

services:
    mydbhost:
        # We use a mariadb image which supports both amd64 & arm64 architecture
        image: mariadb:latest
        # If you really want to use MySQL, uncomment the following line
        #image: mysql:8.0.27
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            # WARNING: hostname is the name of the service in this docker-compose file
            # (hostname is here: mydbhost)
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=mydbuser
            - MYSQL_PASSWORD=mydbpassword
            - MYSQL_ROOT_PASSWORD=mydbroot
        expose:
            - 3306
            - 33060

    nginx-webserver:
        image: nginx:latest
        ports:
            - "${XP_ENV_PORT:-8666}:80"
            # - "${XP_ENV_PORT:-443}:443"
        volumes:
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ${XP_ENV_NGINX_CONF:-./nginx-ssl.conf}:/etc/nginx/conf.d/default.conf
            - ./my-ssl:/etc/nginx/ssl
            # static files for nginx
            - ./app:/var/www/html
            - ./app-php:/var/www/html-php
            - ./app-laravel:/var/www/html-laravel
            - ./app-symfony:/var/www/html-symfony
            - ./app-nest:/var/www/html-nest
            - ./app-directus:/var/www/html-directus
            - ./app-fastify:/var/www/html-fastify
            - ./app-nuxt/.output:/var/www/html-nuxt
        restart: always
        links:
            - php-fpm
        depends_on:
            - mydbhost
            - php-fpm
            - php-fpm2
            - php-fpm3
            - php-fpm4
            - node-directus
            - node-nest
            - node-fastify

    php-fpm:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    php-fpm2:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app-php:/var/www/html-php
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always
        environment:
            - APP_MODE=docker
            # WARNING: hostname is the name of the service in this docker-compose file
            # (hostname is here: mydbhost)
            - MYSQL_HOST=mydbhost
            # - MYSQL_DATABASE=mydb
            - MYSQL_DATABASE=app-php
            - MYSQL_USER=root
            - MYSQL_PASSWORD=mydbroot
            # - MYSQL_ROOT_PASSWORD=mydbroot

    php-fpm3:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app-laravel:/var/www/html-laravel
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    php-fpm4:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app-symfony:/var/www/html-symfony
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    node-directus:
        image: directus/directus:latest
        restart: always
        ports:
            - 8555:8055
        volumes:
            - ./my-data/directus/database:/directus/database
            - ./my-data/directus/uploads:/directus/uploads
        environment:
            TELEMETRY: false
            KEY: 'replace-with-random-value'
            SECRET: 'replace-with-random-value'
            ADMIN_EMAIL: 'admin@example.com'
            ADMIN_PASSWORD: 'd1r3ctu5'
            DB_CLIENT: 'sqlite3'
            DB_FILENAME: '/directus/database/db-directus.sqlite'
            WEBSOCKETS_ENABLED: true
            CORS_ENABLED: true
            CORS_ORIGIN: '*'

    node-nest:
        build: app-nest
        restart: always
        volumes:
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data

    node-fastify:
        build: app-fastify
        restart: always
        volumes:
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data

volumes:
    db_data:
