version: "3.9"

services:

    nginx-webserver:
        image: nginx:latest
        ports:
            - "${XP_ENV_PORT:-8666}:80"
            - "${XP_ENV_PORT:-443}:443"
        volumes:
            - ./app:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ${XP_ENV_NGINX_CONF:-./nginx-ssl.conf}:/etc/nginx/conf.d/default.conf
            - ./my-ssl:/etc/nginx/ssl
        restart: always
        links:
            - php-fpm

    php-fpm:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    php-fpm2:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app-php:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    php-fpm3:
        build: ../image-php-fpm-jupyter
        volumes:
            - ./app-laravel:/var/www/html
            - ${XP_ENV_DATA_DIR:-./my-data}:/var/www/my-data
            - ./root-setup:/root/setup
        restart: always

    node-directus:
        image: directus/directus:latest
        restart: always
        ports:
            - 8555:8055
        volumes:
            - ./my-data/directus/database:/directus/database
            - ./my-data/directus/uploads:/directus/uploads
        environment:
            TELEMETRY: false
            KEY: 'replace-with-random-value'
            SECRET: 'replace-with-random-value'
            ADMIN_EMAIL: 'admin@example.com'
            ADMIN_PASSWORD: 'd1r3ctu5'
            DB_CLIENT: 'sqlite3'
            DB_FILENAME: '/directus/database/db-directus.sqlite'
            WEBSOCKETS_ENABLED: true
            CORS_ENABLED: true
            CORS_ORIGIN: '*'
        links:
            - nginx-webserver

    node-nest:
        build: app-nest
        restart: always
